audit_retention_days: 90
conservative_mode: true
enable_llm_analysis: true
llm_analysis_timeout: 30
max_command_length: 200
risk_thresholds:
  auto_approve_below: 0.3
  auto_reject_above: 0.9
  require_human_above: 0.7
whitelist_auto_update: true
